/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** Validate a plugin id (reverse-domain, path-traversal-safe). Throws on invalid. */
export declare function validatePluginId(id: string): void
/**
 * Parse and fully validate a `manifest.json` string (id, semver, per-kind
 * runnable contracts). Returns the normalized manifest JSON, or throws.
 */
export declare function parseAndValidateManifest(json: string): string
/**
 * The JSON Schema for a `manifest.json`, as a JSON string. Derived from the Rust
 * types, so it never drifts from what the core validates.
 */
export declare function pluginManifestJsonSchema(): string
/** Resolve the effective gateway base URL (`RYU_GATEWAY_URL` or the default). */
export declare function resolveGatewayUrl(): string
/** Resolve the optional gateway bearer token (`RYU_GATEWAY_TOKEN`), or null. */
export declare function resolveGatewayToken(): string | null
/** Throw if `url` points at a blocked direct-provider endpoint (egress rule). */
export declare function assertAllowedEgress(url: string): void
/** A chat message (`role` is "system" | "user" | "assistant"). */
export interface ChatMessage {
  role: string
  content: string
}
/** A non-streaming chat completion result. */
export interface ChatResult {
  content: string
  finishReason?: string
  promptTokens?: number
  completionTokens?: number
  totalTokens?: number
}
/** A streaming chat delta passed to the `stream` callback. */
export interface ChatDelta {
  content: string
  finishReason?: string
}
/** One embedding vector with its position in the input batch. */
export interface Embedding {
  index: number
  vector: Array<number>
}
/** The result of an embedding request: one vector per input (in input order). */
export interface EmbeddingResult {
  embeddings: Array<Embedding>
  promptTokens?: number
  totalTokens?: number
}
/**
 * A gateway-mandatory model client. Every call routes through the Ryu gateway;
 * direct-provider base URLs are rejected at construction.
 */
export declare class ModelClient {
  /**
   * Create a client for `model`. `baseUrl`/`token` default to
   * `RYU_GATEWAY_URL` / `RYU_GATEWAY_TOKEN`.
   */
  constructor(model: string, baseUrl?: string | undefined | null, token?: string | undefined | null)
  /** Non-streaming chat completion. Resolves with the full reply. */
  chat(messages: Array<ChatMessage>): Promise<ChatResult>
  /**
   * Streaming chat completion. Invokes `callback(err, delta)` for each SSE
   * delta, then once more with `delta = null` to signal clean completion;
   * `err` is set if the stream fails. Returns after dispatch (the stream
   * drains on the addon's tokio runtime).
   */
  stream(messages: Array<ChatMessage>, callback: (err: Error | null, arg: ChatDelta | undefined | null) => any): void
}
/**
 * A gateway-mandatory embedding client. Every call routes through the Ryu
 * gateway; direct-provider base URLs are rejected at construction.
 */
export declare class EmbeddingClient {
  /**
   * Create an embedding client for `model`. `baseUrl`/`token` default to
   * `RYU_GATEWAY_URL` / `RYU_GATEWAY_TOKEN`.
   */
  constructor(model: string, baseUrl?: string | undefined | null, token?: string | undefined | null)
  /** Embed a batch of texts, resolving with one vector per input (in order). */
  embed(inputs: Array<string>): Promise<EmbeddingResult>
}
